# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

# Auto-fix: Ensure baml_src path is always resolved correctly relative to this project
import os
from pathlib import Path

# Fix globals.py to use absolute paths before it's imported
_this_file = Path(__file__).absolute()
_baml_client_dir = _this_file.parent
_globals_py = _baml_client_dir / "globals.py"

if _globals_py.exists():
    _globals_content = _globals_py.read_text()
    # Check if it needs fixing (uses relative "baml_src" path)
    if '"baml_src"' in _globals_content and "_baml_src_dir" not in _globals_content:
        # Fix the path resolution
        if "from pathlib import Path" not in _globals_content:
            _globals_content = _globals_content.replace(
                "import os",
                "import os\nfrom pathlib import Path"
            )
        
        # Replace relative path with absolute path resolution
        _replacement = '''# Resolve baml_src path relative to this file's location to ensure we use the correct project's BAML files
_baml_client_dir = Path(__file__).parent.absolute()
_baml_src_dir = _baml_client_dir.parent / "baml_src"

DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME = BamlRuntime.from_files(
  str(_baml_src_dir),'''
        _globals_content = _globals_content.replace(
            'DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME = BamlRuntime.from_files(\n  "baml_src",',
            _replacement
        )
        _globals_py.write_text(_globals_content)


__version__ = "0.213.0"

try:
  from baml_py.safe_import import EnsureBamlPyImport
except ImportError:
  raise ImportError(f"""Update to baml-py required.
Version of baml_client generator (see generators.baml): {__version__}

Please upgrade baml-py to version "{__version__}".

$ pip install baml-py=={__version__}
$ uv add baml-py=={__version__}

If nothing else works, please ask for help:

https://github.com/boundaryml/baml/issues
https://boundaryml.com/discord
""") from None


with EnsureBamlPyImport(__version__) as e:
  e.raise_if_incompatible_version(__version__)

  from . import types
  from . import tracing
  from . import stream_types
  from . import config
  from .config import reset_baml_env_vars
  
  from .sync_client import b
  
  from . import watchers


# FOR LEGACY COMPATIBILITY, expose "partial_types" as an alias for "stream_types"
# WE RECOMMEND USERS TO USE "stream_types" INSTEAD
partial_types = stream_types

__all__ = [
  "b",
  "stream_types",
  "partial_types",
  "tracing",
  "types",
  "reset_baml_env_vars",
  "config",
  "watchers",
]