# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class NextJSProjectComponent(BaseModel):
    type: typing.Optional[types.ComponentType] = None
    command: typing.Optional[types.CommandType] = None
    filePath: typing.Optional[str] = None
    dependencies: typing.List[str]
    specific_instructions: typing.List[str]
    input_validation: typing.Optional[str] = None
    error_handling: typing.Optional[str] = None
    design_guidelines: typing.Optional[str] = None
    test_requirements: typing.List[types.TestType]
    analytics_events: typing.List[str]

class ProjectStructure(BaseModel):
    components: typing.List["NextJSProjectComponent"]
    color_palette: typing.Optional[str] = None
    entry_point: typing.Optional[str] = None
    package_dependencies: typing.List[str]
    file_structure: typing.List[str]
    implementation_order: typing.List[str]
    design_system: typing.Optional[types.DesignSystem] = None
    analytics_provider: typing.Optional[types.AnalyticsProvider] = None
    testing_setup: typing.Optional[str] = None

class RouteGeneratorOutput(BaseModel):
    componentType: typing.Optional[types.ComponentType] = None
    routeName: typing.Optional[str] = None
    dependencies: typing.List[str]
    final_code: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
