# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ProjectComponent": types.ProjectComponent,
    "stream_types.ProjectComponent": stream_types.ProjectComponent,

    "types.ProjectStructure": types.ProjectStructure,
    "stream_types.ProjectStructure": stream_types.ProjectStructure,

    "types.RouteGeneratorOutput": types.RouteGeneratorOutput,
    "stream_types.RouteGeneratorOutput": stream_types.RouteGeneratorOutput,


    "types.CommandType": types.CommandType,

    "types.ComponentType": types.ComponentType,

}