# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (5)
# #########################################################################

class AnalyticsProvider(str, Enum):
    Posthog = "Posthog"
    Mixpanel = "Mixpanel"
    Custom = "Custom"
    NoAnalytics = "NoAnalytics"

class CommandType(str, Enum):
    CreateFile = "CreateFile"
    UpdateFile = "UpdateFile"
    DeleteFile = "DeleteFile"

class ComponentType(str, Enum):
    Route = "Route"
    Middleware = "Middleware"
    Utility = "Utility"
    Configuration = "Configuration"
    Model = "Model"
    Service = "Service"
    Component = "Component"
    Page = "Page"
    Layout = "Layout"
    Admin = "Admin"

class DesignSystem(str, Enum):
    Shadcn = "Shadcn"
    Material = "Material"
    Antd = "Antd"
    Custom = "Custom"
    NoDesignSystem = "NoDesignSystem"

class TestType(str, Enum):
    Unit = "Unit"
    Integration = "Integration"
    E2e = "E2e"

# #########################################################################
# Generated classes (4)
# #########################################################################

class FeatureTemplate(BaseModel):
    name: str
    description: str
    components: typing.List[str]
    dependencies: typing.List[str]

class ProjectComponent(BaseModel):
    type: ComponentType
    command: CommandType
    filePath: str
    current_code: str
    name: str
    description: str
    dependencies: typing.List[str]
    specific_instructions: str
    expected_behavior: str
    input_validation: str
    error_handling: str
    example_usage: str
    design_guidelines: str
    test_requirements: typing.List[TestType]
    analytics_events: typing.List[str]

class ProjectStructure(BaseModel):
    components: typing.List["ProjectComponent"]
    entry_point: str
    package_dependencies: typing.List[str]
    file_structure: typing.List[str]
    implementation_order: typing.List[str]
    design_system: DesignSystem
    analytics_provider: AnalyticsProvider
    feature_templates: typing.List["FeatureTemplate"]
    testing_setup: str

class RouteGeneratorOutput(BaseModel):
    componentType: ComponentType
    routeName: str
    dependencies: typing.List[str]
    final_code: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
