# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class CommandType(str, Enum):
    CreateFile = "CreateFile"
    UpdateFile = "UpdateFile"
    DeleteFile = "DeleteFile"

class ComponentType(str, Enum):
    Route = "Route"
    Middleware = "Middleware"
    Utility = "Utility"
    Configuration = "Configuration"
    Model = "Model"
    Service = "Service"

# #########################################################################
# Generated classes (3)
# #########################################################################

class ProjectComponent(BaseModel):
    type: ComponentType
    command: CommandType
    filePath: str
    current_code: str
    name: str
    description: str
    dependencies: typing.List[str]
    specific_instructions: str
    expected_behavior: str
    input_validation: str
    error_handling: str
    example_usage: str

class ProjectStructure(BaseModel):
    components: typing.List["ProjectComponent"]
    entry_point: str
    package_dependencies: typing.List[str]
    file_structure: typing.List[str]
    implementation_order: typing.List[str]

class RouteGeneratorOutput(BaseModel):
    componentType: ComponentType
    routeName: str
    dependencies: typing.List[str]
    final_code: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
